chore: configure `tsup` as bundler
FurryR/mirai-foxes pull request #62
Opened 2022-12-30 16:23 UTC by hydrati

2022-12-30 16:29 UTC, hydrati commented
@FurryR Ready to review.

2022-12-31 03:54 UTC, FurryR commented
请删除连带。

2022-12-31 04:02 UTC, FurryR requested changes
package-lock.json 兼容性问题
是否考虑 Downgrade 以支持旧版本的 Node.js？

2022-12-31 04:07 UTC, hydrati commented
@FurryR 
> 是否考虑 Downgrade 以支持旧版本的 Node.js？

库不需要考虑这个吧，downgrade这种事情一般交给用户在打包时转译。

2022-12-31 04:20 UTC, FurryR approved these changes
No error

2023-05-21 13:45 UTC, FurryR commented
非常抱歉非常抱歉！！！一直在更 [Awacorn](https://github.com/FurryR/Awacorn) 导致没认真解决这个 pr 的问题。非常对不起。

...但说实话我其实是写 C++ 11 的...虽然写出来的东西也没什么人看就是了。嘛，被极少一部分知道我的人敬仰何尝不可。

2023-07-24 08:14 UTC, merged

2023-07-24 17:28 UTC, hydrati commented
@FurryR 没关系的ww（好像我也忘了）